/* Generated By:JavaCC: Do not edit this line. mashaTreeConstants.java Version 5.0 */
package MASHA_Language_Tree;

public interface mashaTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTATEMENT = 1;
  public int JJTDECLERATION = 2;
  public int JJTARITHMETIC_STMT = 3;
  public int JJTDECLERE_VAR = 4;
  public int JJTLOGICAL_STMT = 5;
  public int JJTUNARY_LOGICAL_STMT = 6;
  public int JJTBINARY_LOGICAL_STMT = 7;
  public int JJTCONDITIONAL_STMT = 8;
  public int JJTELSE_STMT = 9;
  public int JJTCOMPARISON_STMET = 10;
  public int JJTLOOP = 11;
  public int JJTUNTIL = 12;
  public int JJTFUN = 13;
  public int JJTLIST = 14;
  public int JJTID = 15;
  public int JJTNUMBER = 16;
  public int JJTARTIMATIC_OPERATION = 17;
  public int JJTLOGICAL_OPERATION = 18;
  public int JJTCOMPARISON_OPERATION = 19;
  public int JJTFULL_STOP = 20;
  public int JJTASSIGNMENT = 21;
  public int JJTSTRING = 22;
  public int JJTPLUS = 23;
  public int JJTMINUS = 24;
  public int JJTMULTIPLY = 25;
  public int JJTDIVIDE = 26;
  public int JJTINT = 27;
  public int JJTFLOAT = 28;
  public int JJTLEFT_PAR = 29;
  public int JJTRIGHT_PAR = 30;
  public int JJTIF = 31;
  public int JJTCOLON = 32;
  public int JJTELSE = 33;
  public int JJTLEFT_SQR_BRACKT = 34;
  public int JJTRIGHT_SQR_BRACKT = 35;
  public int JJTSTATIC_ID = 36;
  public int JJTVARIABLE_ID = 37;
  public int JJTCONSTANT_ID = 38;
  public int JJTAND = 39;
  public int JJTOR = 40;
  public int JJTXOR = 41;
  public int JJTNOT = 42;
  public int JJTEQUAL = 43;
  public int JJTINEQUAL = 44;
  public int JJTLESS_THAN = 45;
  public int JJTLESS_OR_EQUAL = 46;
  public int JJTGREAT_THAN = 47;
  public int JJTGREAT_OR_EQUAL = 48;
  public int JJTLIST_ELEMENTS = 49;
  public int JJTVAR = 50;


  public String[] jjtNodeName = {
    "Start",
    "statement",
    "decleration",
    "arithmetic_stmt",
    "declere_VAR",
    "logical_stmt",
    "unary_logical_stmt",
    "Binary_logical_stmt",
    "conditional_stmt",
    "else_stmt",
    "comparison_stmet",
    "loop",
    "until",
    "fun",
    "list",
    "ID",
    "number",
    "artimatic_operation",
    "logical_operation",
    "comparison_operation",
    "FULL_STOP",
    "ASSIGNMENT",
    "STRING",
    "PLUS",
    "MINUS",
    "MULTIPLY",
    "DIVIDE",
    "INT",
    "FLOAT",
    "LEFT_PAR",
    "RIGHT_PAR",
    "IF",
    "COLON",
    "ELSE",
    "LEFT_SQR_BRACKT",
    "RIGHT_SQR_BRACKT",
    "STATIC_ID",
    "VARIABLE_ID",
    "CONSTANT_ID",
    "AND",
    "OR",
    "XOR",
    "NOT",
    "EQUAL",
    "INEQUAL",
    "LESS_THAN",
    "LESS_OR_EQUAL",
    "GREAT_THAN",
    "GREAT_OR_EQUAL",
    "LIST_ELEMENTS",
    "VAR",
  };
}
/* JavaCC - OriginalChecksum=7f4ea8d3557dc9d1322b1f5f7414bc43 (do not edit this line) */
